apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonali-intellect-demo
  labels:
    app.kubernetes.io/name: sonali-intellect-demo-cicd-gitops
    app.kubernetes.io/part-of: sonali-intellect-training

