apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: si-demo-staging
resources:
  - ../../base
images:
  - name: demo.goharbor.io/si_demo_harbor/sonali-intellect-demo-cicd-gitops
    newName: harbor.example.com/sonali-intellect/sonali-intellect-demo-cicd-gitops
    digest: sha256:1111111111111111111111111111111111111111111111111111111111111111

