apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonali-intellect-demo-local
  namespace: argocd
spec:
  project: sonali-intellect-training
  source:
    repoURL: https://github.com/AmjadHossainRahat/sonali-intellect-demo-cicd-gitops.git
    targetRevision: main
    path: kubernetes/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: si-demo-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
