apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: si-demo-local
resources:
- namespace.yaml
- ../../base
images:
- digest: sha256:9042a97b1864111c356709d9ba26ab7d9bbc4ab5a0037af7f6f3a335de064bcb
  name: demo.goharbor.io/si_demo_harbor/sonali-intellect-demo-cicd-gitops
  newName: demo.goharbor.io/si_demo_harbor/sonali-intellect-demo-cicd-gitops
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: sonali-intellect-demo
