apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: si-demo-local
resources:
  - namespace.yaml
  - ../../base
images:
  - name: demo.goharbor.io/si_demo_harbor/sonali-intellect-demo-cicd-gitops
    digest: sha256:8d245ae4481dcb8543095c04cf1f209f57936bfc0e8c88535d3662c587c44832
patches:
  - target:
      kind: Deployment
      name: sonali-intellect-demo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

