apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: si-demo-local
resources:
- namespace.yaml
- ../../base
images:
- digest: sha256:70af9c9ad759e41554d465818f9162ee10309e7d9fd53159826c39209cdb13e7
  name: demo.goharbor.io/si_demo_harbor/sonali-intellect-demo-cicd-gitops
  newName: demo.goharbor.io/si_demo_harbor/sonali-intellect-demo-cicd-gitops
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: sonali-intellect-demo
